# -*- coding: utf-8 -*-
"""cluster_blobs.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1v1757nEoZps5HEJP8GvMi2e7wgt87xea
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

d1=pd.read_csv("cluster_blobs.csv")
d1.head()

from sklearn.preprocessing import StandardScaler
from sklearn.metrics import silhouette_score

z1= StandardScaler()
d1[["X1","X2"]]=z1.fit_transform(d1[["X1","X2"]])

from sklearn.neighbors import NearestNeighbors

neigh = NearestNeighbors(n_neighbors=2)
nbrs = neigh.fit(d1)
distances, indices = nbrs.kneighbors(d1)
distances = np.sort(distances, axis=0)
distances = distances[:,1]
plt.rcParams['figure.figsize'] = 8,8
plt.plot(distances)

from sklearn.cluster import DBSCAN
db1 = DBSCAN(eps = 0.1,min_samples = 10).fit(d1[['X1','X2']])
from sklearn.cluster import KMeans
km1 = KMeans(3).fit(d1[['X1','X2']]).labels_
dbs1=db1.labels_
plt.scatter(d1['X1'],d1['X2'],c=dbs1,cmap='rainbow')
plt.title('DBSCAN')
plt.show()
plt.scatter(d1['X1'],d1['X2'],c=km1,cmap='rainbow')
plt.title('Kmeans')
plt.show()

silhouette_score(d1[["X1","X2"]],km1)

silhouette_score(d1[["X1","X2"]],dbs1)

