# -*- coding: utf-8 -*-
"""cluster_circles.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sXAA8zWM33vIzvk09RJ0aynWH47H7Sih
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

d3=pd.read_csv("cluster_circles.csv")
d3.head()

from sklearn.preprocessing import StandardScaler
z3= StandardScaler()
d3[["X1","X2"]]=z3.fit_transform(d3[["X1","X2"]])

from sklearn.neighbors import NearestNeighbors

neigh = NearestNeighbors(n_neighbors=2)
nbrs = neigh.fit(d3)
distances, indices = nbrs.kneighbors(d3)
distances = np.sort(distances, axis=0)
distances = distances[:,1]
plt.rcParams['figure.figsize'] = 7,7
plt.plot(distances)

from sklearn.cluster import DBSCAN
db3 = DBSCAN(eps = 0.2,min_samples = 19).fit(d3[['X1','X2']])
from sklearn.cluster import KMeans
km3 = KMeans(2).fit(d3[['X1','X2']]).labels_
dbs3=db3.labels_
plt.scatter(d3['X1'],d3['X2'],c=dbs3,cmap='rainbow')
plt.title('DBSCAN')
plt.show()
plt.scatter(d3['X1'],d3['X2'],c=km3,cmap='rainbow')
plt.title('Kmeans')
plt.show()

from sklearn.metrics import silhouette_score

silhouette_score(d3[["X1","X2"]],km3)

silhouette_score(d3[["X1","X2"]],dbs3)

